#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function die {
	echo "[EE] $*"
	exit 1
}

PACKAGE="poet"

TOOL="${PACKAGE}/__main__.py"
SRC="src"

PROJECT_DIR="${SCRIPT_DIR}/"
TOOL_PATH="${PROJECT_DIR}/$SRC/${TOOL}"

MSG="Cannot find the uv Python project manager. Please see https://docs.astral.sh/uv/getting-started/installation/"
which uv > /dev/null || die "$MSG"

UV_CMD="run python -m ${PACKAGE}"

exec uv --quiet --project "${PROJECT_DIR}" ${UV_CMD} "$@"
