#!/usr/bin/env python3

#################################
## Dependencies check
#################################

import sys, os, pkg_resources

dependencies = [
    "pyyaml",
    "joblib",
]
try:
    pkg_resources.require(dependencies)
except pkg_resources.DistributionNotFound as error:
    print(error)
    sys.exit(-1)


#################################
## Running POET
#################################

# Temporary hack: the name "pipeline" is ill-chosen and can lead to name
# clashes with globally installed modules that also happen to be called
# "pipeline". As a workaround until POET is refactored, we're adding the
# directory with the code explicitly to the module path.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))
if SCRIPT_DIR.endswith("src"):
    from src.pipeline import main
else:
    from POET.src.pipeline import main

main.run_poet()
